import Image from "next/image";

export const metadata = {
  title: "About | Blogs",
  description: "Generated by Next JS, Tailwind CSS and MongoDB",
};

const AboutPage = () => {
  return (
    <section className="bg-gray-100 dark:bg-[#181818] p-5 pb-0">
      <div className="sm:flex items-center justify-center md:px-12 bg-white dark:bg-dark">
        <div className="sm:w-1/2 p-10">
          <div className="image object-center text-center">
            <Image
              src="/images/contact.png"
              width={1500}
              height={1000}
              alt="About"
              placeholder="blur"
              blurDataURL="/images/placeholder.png"
            />
          </div>
        </div>
        <div className="sm:w-1/2 p-5">
          <div className="text">
            <span className="text-gray-500 dark:text-gray-300 border-b-2 border-primary uppercase">
              About us
            </span>
            <h2 className="my-4 font-bold text-3xl dark:text-gray-100  sm:text-4xl ">
              About <span className="text-primary">Our Company</span>
            </h2>
            <p className="text-gray-700 dark:text-gray-300">
              Dive into a world of engaging blogs and thought-provoking content
              on Writers’ Thoughts. Whether you’re looking for insightful
              articles, compelling stories, or the latest trends, our site
              offers a curated selection of posts that cater to diverse
              interests. Explore, read, and connect with a community of
              passionate writers and readers. Join us and let your curiosity
              lead the way!
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AboutPage;
