import { SessionProvider } from "next-auth/react";
import ContactForm from "./_component/ContactForm";

export const metadata = {
  title: "Contact | Blogs",
  description: "Generated by Next JS, Tailwind CSS and MongoDB",
};

const ContactPage = () => {
  return (
    <SessionProvider>
      <ContactForm />
    </SessionProvider>
  );
};

export default ContactPage;
