import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Nav";
import SplashScreen from "@/components/common/SplashScreen";
import { UserProvider } from "@/context/UserContext";
import { SessionProvider } from "next-auth/react";
import { Montserrat } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Blogs | Writers Thoughts",
  description: "Generated by Next JS, Tailwind CSS and MongoDB",
};

// RootLayout component is the main layout wrapper for the application.
// It sets up global providers, layout structure, and page metadata.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={montserrat.className + " bg-gray-100 dark:bg-[#181818] "}
      >
        {/* SplashScreen is used to display a loading screen until the main content is ready. */}
        <SplashScreen>
          {/* SessionProvider makes the user's session data available throughout the app. */}
          <SessionProvider>
            {/* UserProvider is a custom context provider for managing user-related state. */}
            <UserProvider>
              {/* Navbar is the navigation bar displayed at the top of every page. */}
              <Navbar />
              {/* Render the children prop to display the main content of each page. */}
              {children}
              {/* Footer is the footer component displayed at the bottom of every page. */}
              <Footer />
            </UserProvider>
          </SessionProvider>
        </SplashScreen>

        {/* ToastContainer is used to display toast notifications in the app. */}
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar
        />
        {/* NextTopLoader is a progress bar that appears at the top of the page during navigation. */}
        <NextTopLoader color="#eb175c" showSpinner={false} />
        {/* Placeholder section for dynamically injecting search results or other content. */}
        <section id="search-result"></section>
      </body>
    </html>
  );
}
